# -*- coding: utf-8 -*-
"""03_if_statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19s73gI1_EWP_yBbKMFDqa8Bpsg-LaBuG
"""

# Write a program that prints the first 20 even numbers. There are several correct approaches, but they all use a loop of some sort. Do no write twenty print statements

# The first even number is 0:

# 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38

def main():

    for i in range(20):
        print(i * 2)

if __name__ == '__main__':
    main()

# Write a program which asks a user for their age and lets them know if they can or can't vote in the following three fictional countries.

# Around the world, different countries have different voting ages. In the fictional countries of Peturksbouipo, Stanlau, and Mayengua, the voting ages are very different:

# the voting age in Peturksbouipo is 16 (in real life, this is the voting age in, for example, Scotland, Ethiopia, and Austria)

# the voting age in Stanlau is 25 (in real life this is the voting age in the United Arab Emirates)

# the voting age in Mayengua is 48 (in real life, as far as we can tell, this isn't the voting age anywhere)

# Your code should prompt the for their age and print whether or not they can vote in Peturksbouipo, Stanlau, or Mayengua.

# Here's a sample run of the program (user input is in blue):

# How old are you? 20 You can vote in Peturksbouipo where the voting age is 16. You cannot vote in Stanlau where the voting age is 25. You cannot vote in Mayengua where the voting age is 48



PETURKSBOUIPO_AGE : int = 16
STANLAU_AGE : int = 25
MAYENGUA_AGE : int = 48

def main():
    user_age: int = int(input("How old are you? "))

    if user_age >= PETURKSBOUIPO_AGE:
        print("You can vote in Peturksbouipo where the voting age is " + str(PETURKSBOUIPO_AGE) + ".")
    else:
        print("You cannot vote in Peturksbouipo where the voting age is " + str(PETURKSBOUIPO_AGE) + ".")

    if user_age >= STANLAU_AGE:
        print("You can vote in STANLAU where the voting age is " + str(STANLAU_AGE) + ".")
    else:
        print("You cannot vote in STANLAU where the voting age is " + str(STANLAU_AGE) + ".")

    if user_age >= MAYENGUA_AGE:
        print("You can vote in MAYENGUA_ where the voting age is " + str(MAYENGUA_AGE) + ".")
    else:
        print("You cannot vote in MAYENGUA_ where the voting age is " + str(MAYENGUA_AGE) + ".")


if __name__ == '__main__':
    main()

# Write a program that reads a year from the user and tells whether a given year is a leap year or not.

def main():
    year:int = int(input("Please enter a year "))
    if year % 4 == 0:
      if year % 100 == 0:
        if year % 400 == 0:
          print("it is a leap year")
        else:
          print("it is not a leap year")
      else:
        print("it is a leap year")
    else:
      print("it is not a leap year")
if __name__ == '__main__':
    main()

# Write a program which asks the user how tall they are and prints whether or not they're taller than a pre-specified minimum height.

# In amusement parks (ah, the good old pre-pandemic days...), rollercoasters frequently have minimum height requirements for safety reasons. Assume for now that the minimum height is 50 of whatever height unit you'd like

# Here's two sample runs (user input is in bold italics):

# How tall are you? 100

# You're tall enough to ride!

# How tall are you? 10

# You're not tall enough to ride, but maybe next year!

# (For an extra challenge, write code which will repeatedly ask a user how tall they are and tell them whether or not they're tall enough to ride, until the user doesn't enter a height at all, in which case the program stops. Curious about how to do this? See the function tall_enough_extension() in the solution code!)

MINIMUM_HEIGHT : int = 50
def tall_enough_extension():
  while True:
    height: int = int(input("How tall are you? "))
    if height >= MINIMUM_HEIGHT:
        print("You're tall enough to ride!")
    else:
        print("You're not tall enough to ride, but maybe next year!")


def main():
    tall_enough_extension()
if __name__ == '__main__':
    main()

# Print 10 random numbers in the range 1 to 100.

# Here is an example run:

# 45 79 61 47 52 10 16 83 19 12

# Each time you run your program you should get different numbers

# 81 76 70 1 27 63 96 100 32 92

# Recall that the python random library has a function randint which returns an integer in the range set by the parameters (inclusive). For example this call would produce a random integer between 1 and 6, which could include 1 and could include 6:

# value = random.randint(1, 6)

import random

N_NUMBERS = 10
MIN_VALUE = 1
MAX_VALUE = 100

def main():
    for _ in range(N_NUMBERS):
        value = random.randint(MIN_VALUE, MAX_VALUE)
        print(value, end=" ")

if __name__ == '__main__':
    main()