# -*- coding: utf-8 -*-
"""01_expressions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1efQT6Oaghnvml2wp99XDGa02N2ToxppG
"""

# Simulate rolling two dice, three times. Prints the results of each die roll. This program is used to show how variable scope works.

import random

def roll_dice():
    dice1: int = random.randint(1, 6)
    dice2: int = random.randint(1, 6)
    print(f"Rolled dice: {dice1} and {dice2}")

def main():
    print("Rolling two dice three times...\n")
    for i in range(3):
        print(f"Roll {i + 1}:")
        roll_dice()
        print()  # Blank line for readability

main()

# Write a program that continually reads in mass from the user and then outputs the equivalent energy using Einstein's mass-energy equivalence formula (E stands for energy, m stands for mass, and C is the speed of light:

# E = m * c**2

# Almost 100 years ago, Albert Einstein famously discovered that mass and energy are interchangeable and are related by the above equation. You should ask the user for mass (m) in kilograms and use a constant value for the speed of light -- C = 299792458 m/s.

# Here's a sample run of the program (user input is in bold italics):

# Enter kilos of mass: 100

# e = m * C^2...

# m = 100.0 kg

# C = 299792458 m/s

# 8.987551787368176e+18 joules of energy!

C:int = 299792458

def main():

  mass_in_kg: str = input("Enter kilos of mass: ")
  mass_in_kg: int = float(mass_in_kg)
  energy_in_joules: float = float(mass_in_kg*C**2)

  print("e = m * C^2...")
  print("m = " + str(mass_in_kg) + " kg")
  print("C = " + str(C) + " m/s")

  print(str(energy_in_joules) + " joules of energy!")


if __name__ == '__main__':
    main()

# Converts feet to inches. Feet is an American unit of measurement. There are 12 inches per foot. Foot is the singular, and feet is the plural.

inches_in_foot: int = 12

def main():
    feet: float = float(input("Enter numbers of feet: "))
    inches: float = float(inches_in_foot* feet)
    print("That is", inches, "inches!")


# This provided line is required at the end of
# Python file to call the main() function.
if __name__ == '__main__':
    main()

# Write a program that asks the user for the lengths of the two perpendicular sides of a right triangle and outputs the length of the third side (the hypotenuse) using the Pythagorean theorem!

# The Pythagorean theorem, named after the ancient Greek thinker, Pythagoras, is a fundamental relation in geometry. It states that in a right triangle, the square of the hypotenuse is equal to the sum of the square of the other two sides.

# For instance, let's consider a right triangle ABC, with the right angle located at C. According to the Pythagorean theorem:

# BC ** 2 = AB ** 2 + AC ** 2

# Your code should read in the lengths of the sides AB and AC, and that outputs the length of the hypotenuse (BC). You will probably find math.sqrt() to be useful.

# Here's a sample run of the program (user input is in bold italics):

# Enter the length of AB: 3

# Enter the length of AC: 4

# The length of BC (the hypotenuse) is: 5.0

import math

def main():
    AB : float = float(input("Enter the lenght of side AB: "))
    AC : float = float(input("Enter the lenght of side AC: "))
    BC: float = math.sqrt(AB ** 2 + AC ** 2)

    print(f"The length of BC (the hypotenuse) is: {BC}")


if __name__ == '__main__':
    main()

# Ask the user for two numbers, one at a time, and then print the result of dividing the first number by the second and also the remainder of the division.

# Here's a sample run of the program (user input is in bold italics):

# Please enter an integer to be divided: 5

# Please enter an integer to divide by: 3

# The result of this division is 1 with a remainder of 2

def main():
   num1:int = int(input("Please enter an integer to be divided: "))
   num2:int = int(input("Please enter an integer to  divided: "))
   result: int = int(num1/num2)
   remainder: int = int(num1%num2)
   print(f"The result of this division is {result} with a remainder of {remainder}")

if __name__ == '__main__':
    main()

# Simulate rolling two dice, and prints results of each roll as well as the total.

import random

def main():
   dice1:int = random.randint(1, 6)
   dice2:int = random.randint(1, 6)
   total:int = dice1 + dice2

   print(f"The result of dice 1 is: {dice1}")
   print(f"The result of dice 2 is: {dice2}")
   print(f"The total of both dices is: {total}")

if __name__ == '__main__':
    main()

# Use Python to calculate the number of seconds in a year, and tell the user what the result is in a nice print statement that looks like this (of course the value 5 should be the calculated number instead):

# There are 5 seconds in a year!

# You should use constants for this exercise -- there are 365 days in a year, 24 hours in a day, 60 minutes in an hour, and 60 seconds per minute.

DAYS_PER_YEAR: int = 365
HOURS_PER_DAY: int = 24
MIN_PER_HOUR: int = 60
SEC_PER_MIN: int = 60

def main():

   SECONDS_IN_YEAR: int = DAYS_PER_YEAR * HOURS_PER_DAY * MIN_PER_HOUR * SEC_PER_MIN
   print(f"There are {SECONDS_IN_YEAR} seconds in a year!")

if __name__ == '__main__':
    main()

# Write a program which prompts the user for an adjective, then a noun, then a verb, and then prints a fun sentence with those words!

# Mad Libs is a word game where players are prompted for one word at a time, and the words are eventually filled into the blanks of a word template to make an entertaining story! We've provided you with the beginning of a sentence (the SENTENCE_START constant) which will end in a user-inputted adjective, noun, and then verb.

# Here's a sample run (user input is in bold italics):

# Please type an adjective and press enter. tiny

# Please type a noun and press enter. plant

# Please type a verb and press enter. fly

# Code in Place is fun. I learned to program and used Python to make my tiny plant fly!


def main():

  adjective = input("Enter an adjective: ")
  noun = input("Enter a noun: ")
  verb = input("Enter a verb: ")
  place = input("Enter a place: ")

  story = f"""
  Today I went to the {place}, and I saw a very {adjective} {noun}.
  It suddenly started to {verb} in front of everyone!
  It was the most surprising thing I’ve seen all day."""

  print("\nHere's your Mad Libs story:")
  print(story)
if __name__ == '__main__':
    main()